;METADATA=(Diff=true, UseCommands=true)
[/Script/FortniteGame.FortGameUserSettings]
CosmeticStreamingEnabled=CodeSet_Disabled
FortniteReleaseVersion=9
UnlockConsoleFPS=False
SubGameSelectCount_Athena=12
SubGameLastSelectedTime_Athena=2025.01.17-15.13.56
SubGameSelectCount_Campaign=0
SubGameLastSelectedTime_Campaign=0001.01.01-00.00.00
LastTimeSettingsSnapshotUploaded=2025.01.17-10.11.50
FirstLoginOnDevice=2025.01.04-21.52.45
SafeZone=1.000000
bIsSafeZoneSet=False
CachedPlayerLevel=0
bShowActorsWithSeasonItemTagMapIndicators=True
CachedBattleStars=0
CachedAlienStylePoints=0
CachedStylePoints=0
CachedClaimableRewards=()
CachedHighestBattlePassUnlockedPage=1
bShowCareerTabBang=False
CustomVoiceChatInputDevice=
CustomVoiceChatOutputDevice=
CustomVoiceChatInputDeviceId=
CustomVoiceChatOutputDeviceId=
bMotionBlur=False
bAllowUIParallax=True
bShowGrass=True
bShowFPS=False
bUseGPUCrashDebugging=False
bStopRenderingInBackground=False
bLatencyTweak1=False
LatencyTweak2=1
bLatencyFlash=False
FortAntiAliasingMethod=DLSS
bEnableDLSSFrameGeneration=False
TemporalSuperResolutionQuality=Recommended
DLSSQuality=3
XeSSQuality=2
PotentiallyUpscaledResolutionQuality=0.000000
NeverUpscaledResolutionQuality=100.000000
bUseNanite=False
DesiredGlobalIlluminationQuality=1
DesiredReflectionQuality=1
PreNaniteGlobalIlluminationQuality=1
PreNaniteReflectionQuality=1
bRayTracing=False
b120FpsMode=False
FrontendFrameRateLimit=120
bIsEnergySavingEnabledIdle=True
bIsEnergySavingEnabledFocusLoss=True
EnergySavingLevelFocusLoss=1
DisplayGamma=2.200000
UserInterfaceContrast=1.000000
NamedTimes=(("RankedStartTime_User_ad06f7cfaecf4dea981047d5192a0d53_Track_P3PP3R", 2025.01.17-10.16.51))
NamedCounts=(("SeasonTrailer", 33),("SeasonTrailer_HotfixVer", 7),("EcosystemTrailer", 1),("EcosystemTrailer_HotfixVer", 7),("lastfrontendflow_Fortnite", 33),("lastfrontendflow_Fortnite_HotfixVer", 0),("UEnableMultiFactorModal::ShouldShowMFASplashScreen", 33),("UEnableMultiFactorModal::ShouldShowMFASplashScreen_HotfixVer", 0))
BattlePassOverrideTracker=0
NewestProgressiveCosmeticSetSeen=
CurrentLockerSortsByTag=()
ArchetypeShuffleSelectionBias=()
bLockerHideUnsupportedItems=False
bHasUsedBattlePassCrewUpsellNavButton=False
LastExpectedShopRefreshTime=2025.01.18-00.00.00
bHasSeenItemShop=True
bHasSeenJunoOutfitsFTUE=False
JunoFTUEQuestTrackingDisabledVersion=0
bHasSeenDonutShopSequence=False
DonutIdleGameHighScore=0.000000
RowIdToOfferSeenLevel=(("DragonBallZ12-1.99", OfferSectionVisited),("DragonBallZ12-1.98", ItemShopVisited),("DragonBallZ12-1.97", ItemShopVisited),("DragonBallZ12-1.96", ItemShopVisited),("DragonBallZ12-1.95", ItemShopVisited),("Icons1-5.99", OfferSectionVisited),("Icons1-5.98", OfferSectionVisited),("Icons1-5.97", ItemShopVisited),("ElRubius1.99", ItemShopVisited),("ElRubius1.98", OfferSectionVisited),("ElRubius1.97", ItemShopVisited),("PatrickMahomes.99", ItemShopVisited),("PatrickMahomes.98", ItemShopVisited),("SamuraiStarwars.99", ItemShopVisited),("SamuraiStarwars.98", ItemShopVisited),("SamuraiStarwars.97", ItemShopVisited),("Cyberpunk2077.99", ItemShopVisited),("Cyberpunk2077.98", ItemShopVisited),("Cyberpunk2077.97", ItemShopVisited),("Cyberpunk2077.96", ItemShopVisited),("Hiper.99", ItemShopVisited),("Hiper.98", ItemShopVisited),("Liaqn.99", ItemShopVisited),("Liaqn.98", ItemShopVisited),("SignatureStyle0106.99", ItemShopVisited),("SignatureStyle0106.98", ItemShopVisited),("SignatureStyle0106.97", ItemShopVisited),("SignatureStyle0106.96", ItemShopVisited),("SignatureStyle0106.95", ItemShopVisited),("SignatureStyle0106.94", ItemShopVisited),("WonderWoman.99", ItemShopVisited),("WonderWoman.98", ItemShopVisited),("SuperOG.99", ItemShopVisited),("HolidayFavorites.99", ItemShopVisited),("HolidayFavorites.96", ItemShopVisited),("HolidayFavorites.95", ItemShopVisited),("HolidayFavorites.94", ItemShopVisited),("HolidayFavorites.93", ItemShopVisited),("HolidayFavorites.92", ItemShopVisited),("Winterfest1006.99", ItemShopVisited),("Winterfest1006.98", ItemShopVisited),("Winterfest1006.97", ItemShopVisited),("Winterfest1006.96", ItemShopVisited),("Winterfest1006.95", ItemShopVisited),("Winterfest1006.93", ItemShopVisited),("Winterfest1006.92", ItemShopVisited),("NikeDrop9.99", ItemShopVisited),("TsuzureBoost.99", ItemShopVisited),("JamTracks0106.99", ItemShopVisited),("JamTracks0106.98", ItemShopVisited),("JamTracks0106.97", ItemShopVisited),("SparksInstruments46.99", ItemShopVisited),("SnoopDogg1.99", ItemShopVisited),("SnoopDogg1.98", ItemShopVisited),("SnoopDogg1.97", ItemShopVisited),("AnarchyAcres.99", ItemShopVisited),("BattlePassCrew.1", ItemShopVisited),("BattlePassCrew.3", ItemShopVisited),("BattlePassCrew.4", Unseen),("BattlePassCrew.5", ItemShopVisited),("LimitedTime.1", ItemShopVisited),("LimitedTime.2", ItemShopVisited),("LimitedTime.3", ItemShopVisited),("LimitedTime.4", ItemShopVisited),("LimitedTime.5", ItemShopVisited),("LimitedTime.6", ItemShopVisited),("Shaq.99", Unseen),("Shaq.98", Unseen),("Shaq.97", Unseen),("SignatureStyle0107.99", Unseen),("SignatureStyle0107.98", Unseen),("SignatureStyle0107.97", Unseen),("SignatureStyle0107.96", Unseen),("SignatureStyle0107.95", Unseen),("SignatureStyle0107.94", Unseen),("SignatureStyle0107.93", Unseen),("HolidayFavorites.98", Unseen),("HolidayFavorites.97", Unseen),("Winterfest1007.99", Unseen),("Winterfest1007.98", Unseen),("Winterfest1007.97", Unseen),("Winterfest1007.96", Unseen),("JamTracks0107.99", Unseen),("JamTracks0107.98", Unseen),("JamTracks0107.97", Unseen),("MechaGodzilla.99", Unseen),("MechaGodzilla.98", Unseen),("MechaGodzilla.97", Unseen),("MechaGodzilla.96", Unseen),("Hatsune.99", Unseen),("Hatsune.98", Unseen),("Hatsune.97", Unseen),("SignatureStyle0117.99", Unseen),("SignatureStyle0117.98", Unseen),("SignatureStyle0117.97", Unseen),("SignatureStyle0117.96", Unseen),("SignatureStyle0117.95", Unseen),("SignatureStyle0117.94", Unseen),("WrapRFDrop7.99", Unseen),("WrapRFDrop7.98", Unseen),("NikeDrop10.99", Unseen),("JamTracks0117.99", Unseen),("JamTracks0117.98", Unseen),("JamTracks0117.97", Unseen),("SparksInstruments48.99", Unseen),("Peregrine.99", Unseen),("Shortquarter1.99", Unseen),("BattlePassCrew.2", Unseen),("LimitedTime.7", Unseen))
LastSelectedIsland=(LinkId=(Mnemonic="playlist_habanero_sunflower_solo",Version=-1),Session=(ID="",JoinInfo=(Joinability=CanNotBeJoinedOrWatched,SessionKey="")),World=(ID="",OwnerId=INVALID,Name=INVTEXT(""),bIsJoinable=False),ProductModes=,Privacy=NoFill,RegionId="ME")
LastPlayedIsland=(LinkId=(Mnemonic="playlist_habanero_sunflower_solo",Version=-1),Session=(ID="895fb13fe5d1488c9652e36bf4c44a32",JoinInfo=(Joinability=CanNotBeJoinedOrWatched,SessionKey="")),World=(ID="",OwnerId=INVALID,Name="",bIsJoinable=False),ProductModes=,Privacy=NoFill,RegionId="ME")
LastSelectedPlaylist=(PlaylistName="NoPlaylist",TournamentId="",EventWindowId="",LinkId=(Mnemonic="playlist_habanero_sunflower_solo",Version=-1),ProductModes=)
LastSelectedFillOption=True
bLastSelectedPrivateMatchOption=False
CustomMatchOptions=()
CreativeOptions=()
bHasSeenCreativePhoneTutorial=False
bHasSeenCreativeHeatmapTutorial=False
CreativeOptionLastUsedCategory=0
CreativeOptionLastUsedIndexInCategory=0
LastSelectedChildActivityMap=()
LastNewsVersionViewedBR=
LastNewsVersionViewedCreative=
LastNewsVersionViewedSTW=
LastPRMEtag=
LastFrontEndBackPlateStageUsed[0]=season3300
LastFrontEndBackPlateStageUsed[1]=default
bEulaAccepted=True
EulaAcceptedUserId=ad06f7cfaecf4dea981047d5192a0d53
LastEulaCheckTime=2025.01.17-10.11.46
HUDLayoutData[0]=(LayoutEntries=)
HUDLayoutData[1]=(LayoutEntries=)
HUDLayoutData[2]=(LayoutEntries=)
ActiveHUDProfileIdentifier=(HUDProfileType=(TagName=""),Guid=00000000000000000000000000000000)
bTimesSeenBacchusLoadTutorial=0
bHasSeenTapToShoot=False
NumTimesSeeingPanningTip=0
FireModeData=(bAutoFireIsEnabled=True,b3DTouchEnabled=False,bTapToShootEnabled=False,bAlwaysShowDedicatedButton=True,FireModeType=Unset)
SimpleMobileStats=(GamesPlayed=18,SecondsPlayed=6839,KillCount=80,BestResult=1,LastReviewPromptDay=0001.01.01-00.00.00,CampaignGamesPlayed=0)
SelectedAndroidAppStore=Unset
AudioOutputDeviceId=
bUseHeadphoneMode=False
InitialBenchmarkState=1
bDisableMouseAcceleration=False
ChosenLoginType=None
SocialImportOptedOutVersion=0
VKImportOptedOutVersion=0
bHasSeenErebusSocialImport=False
bHasSeenFriendImportToast=False
LastSocialImportPromptTime=0001.01.01-00.00.00
bAutoImportFriendEnabled=False
bSeenLetoSellModal=False
SocialImportPromptCountCurrentVersion=0
SocialImportPromptCountAllVersions=0
VKImportPromptCountCurrentVersion=0
VKImportPromptCountAllVersions=0
LastAccountItemWarningTime=0001.01.01-00.00.00
bMultiFactorAuthModalOpOut=False
LastEnableMFAModalPromptTime=0001.01.01-00.00.00
LastVKImportPromptTime=0001.01.01-00.00.00
LastAffiliateToastTime=0001.01.01-00.00.00
FailedInviteMap=()
MobileRecommendationDismissedVersion=0
ShowLiveStreamPictureInPictureInMatchV2=Default
CurrentLivePiPStreamOverrideCounter=0
SelectedFrontEnd=
bNeverShowMobileLink=False
bHasMigratedDownloadSettings=False
bSendAppsFlyerEventOnInstallation=True
bAllowFullGameDownload=False
bAllowCellularDownload=False
LastAutoDownloadHighResTextureReminder=638727058114620000
bAutoLaunchFullGame=False
bAllowDownloadHighResMips=False
ContentQualityLevelSelected=Unset
bAllowLowPowerMode=False
bAllowVideoPlayback=True
MobileFPSMode=Mode_30Fps
MobileQualitySettingsResetDefaultsGUID=
bHasSeenSamsungPressureSensorWarning=False
bNeverDisplaySamsungPressureSensorWarning=False
bHasRecentlySeenBadMatchPopup=False
MatchesSinceLastBadMatchPopup=0
bHasAlreadyRatedOnGooglePlay=False
DaysToSnoozeBeforeNextGooglePlayRating=0
GooglePlayRatingDelayedOccurences=0
ParsleyIdleTime=Minutes_15
bShowTemperature=False
LastGameStartNotificationSentTime=0001.01.01-00.00.00
LastYearForcedDisplayWinterfestInfoButton=0
LastYearWinterfestWasSeen=0
bHasSeenSidekickWelcomePopup=False
bHasSeenLobbyModeSetNotification=False
bHasSeenLobbyModeChangedNotification=False
bHasSeenDiscoveryDetailsModeSetNotification=False
bHasSeenDiscoveryCCUModal=False
bHasSeenCreatorPageFirstTimeTooltip=False
LowInputLatencyModeIsEnabled=True
bNeedsToSeeFireModeSelectionReminder=False
MatchesSinceInitialFireModeSelection=0
LastLaunchPushNotificationState=NotSet
bIsPushNotificationConsentValid=False
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1920
LastUserConfirmedResolutionSizeY=1080
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
AudioQualityLevel=0
LastConfirmedAudioQualityLevel=0
FrameRateLimit=0.000000
DesiredScreenWidth=1280
DesiredScreenHeight=720
LastUserConfirmedDesiredScreenWidth=1280
LastUserConfirmedDesiredScreenHeight=720
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=-1.000000
LastGPUBenchmarkResult=-1.000000
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
ConsumedLinkTokens=Token:fnbraddon

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=2
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=3
sg.LandscapeQuality=2

[/Script/FortniteGame.FortAudioMixSubsystem]
UserMixCurrentValues=0.700000
UserMixCurrentValues=0.000000
UserMixCurrentValues=1.000000
UserMixCurrentValues=1.000000
UserMixCurrentValues=0.100000
UserMixCurrentValues=1.000000
UserMixCurrentValues=0.500000

[ChatSettings]
HideSocialName=False
AutoImportFriends=False
ShowNotifications=True
NeverFadeMessages=False
ShowTimeStamps=True
ShowWhispersInAllTabs=False
ShowCustomTab=True
ShowWhispersTab=False
ShowGlobalTab=True
ShowCombatAndEventsTab=True
ShowClanTabs=True
HideOffline=False
HideOutgoing=False
HideSuggestions=False
HideRecent=False
HideBlocked=True
FilterMatureLanguage=True
DisplayCharacterNames=False
FriendInviteReceivedCueEnabled=True
GameOrPartyInviteReceivedCueEnabled=False
MessageReceivedCueEnabled=True
SoundEnabled=False
ShowTextChat=True
FontSize=1
WindowHeight=0
WindowOpacity=0.5

[D3DRHIPreference]
PreferredRHI=dx11
PreferredFeatureLevel=es31

